name: GH actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  pre-commit-check:
    name: pre-commit check
    runs-on: ubuntu-20.04
    if: github.repository == 'sermojohn/demo-go' 
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: |
          echo "hello world!"
        
