name: GH actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  debug:
    name: debug GH context
    runs-on: ubuntu-20.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Show GitHub context
        run: echo "$GITHUB_CONTEXT"

  pre-commit:
    name: check pre-commit
    runs-on: ubuntu-20.04
    if: github.repository == 'sermojohn/demo-go'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '1.16'
      - name: install go deps
        run: |
          make install-deps
      - uses: pre-commit/action@v2.0.2

  unit-tests:
    name: run unit tests
    runs-on: ubuntu-20.04
    needs: [pre-commit]
    if: github.repository == 'sermojohn/demo-go'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '1.16'
      - name: test
        run: make test

  docker-images:
    name: push docker images
    runs-on: ubuntu-20.04
    needs: [pre-commit, unit-tests]
    if: ${{ github.repository == 'sermojohn/demo-go' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sermojohn/demo-go:latest,sermojohn/demo-go:v1.3
