name: GH actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  pre-commit-check:
    name: pre-commit check
    if: github.repository == "sermojohn/demo-go" 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: |
          echo hello world!
        
